name: Docker Publish x64

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number of new release'     
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PW }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build image
        run: docker buildx build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VERSION="${{ github.event.inputs.version }}" --file Dockerfile.dev --tag f0rc3/barcodebuddy-docker:latest-dev --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64  .

      - name: Push image
        run: docker push f0rc3/barcodebuddy-docker:latest-dev
