#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
----------------------------------------------------------------------------

 ______                            _       ______            _     _       
(____  \                          | |     (____  \          | |   | |      
 ____)  ) ____  ____ ____ ___   _ | | ____ ____)  )_   _  _ | | _ | |_   _ 
|  __  ( / _  |/ ___) ___) _ \ / || |/ _  )  __  (| | | |/ || |/ || | | | |
| |__)  | ( | | |  ( (__| |_| ( (_| ( (/ /| |__)  ) |_| ( (_| ( (_| | |_| |
|______/ \_||_|_|   \____)___/ \____|\____)______/ \____|\____|\____|\__  |
                                                                    (____/ 

                   Thank you for using our Docker image! 

                  https://github.com/Forceu/barcodebuddy
               https://github.com/Forceu/barcodebuddy-docker
---------------------------------------------------------------------------
'

chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
